on: 
  workflow_dispatch:

name: Testing GitHubAPI package

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-artifacts:
    name: Create
    runs-on: ubuntu-20.04
    steps:
    - name: Create files
      run: |
        echo "This is file 1" > file1.txt
        echo "I am file 2" > file2.txt
        
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: text-files
        path: |
          file*.txt
          
  consume-artifacts:
    name: Consume
    needs: create-artifacts
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: text-files
        
    - name: Print contents
      run: |
        echo "File 1:"
        cat file1.txt
        echo "File 2:"
        cat file2.txt
    
  delete-artifacts:
    name: Delete
    needs: consume-artifacts
    runs-on: ubuntu-20.04
    container:
      image: bioconductor/bioconductor_docker:RELEASE_3_15
    steps:
    - name: Install R packages
      run: |
        BiocManager::install('grimbough/GitHubAPI')
      shell: Rscript {0}
      
    - name: List artifacts
      run: |
        Rscript -e "GitHubAPI::listArtifacts(owner = ${GITHUB_REPOSITORY_OWNER}, repo = basename(${GITHUB_REPOSITORY}), run_id = ${GITHUB_RUN_ID})
