on: 
  workflow_dispatch:
  push:

name: Installing MASS

jobs:
  install-mass:
    runs-on: ubuntu-20.04
    steps:  
    
    - uses: actions/checkout@v2
    
    - uses: r-lib/actions/setup-r@v2
    
    - name: Install pack
      run: install.packages('pak', dependencies = TRUE)
      shell: Rscript {0}
      
    - name: Install MASS
      run: pak::pkg_install("MASS")
      shell: Rscript {0}
      
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 1
        extra-packages: |
          MASS
          nnet
