on: 
  workflow_dispatch:
  push:

name: Installing MASS

jobs:
  install-mass:
    runs-on: ubuntu-20.04
    steps:  
    
    - name: Install system dependencies
      run: | 
        sudo apt-get update -y && sudo apt-get install libcurl4-openssl-dev -y
    
    - uses: actions/checkout@v2
    
    - uses: r-lib/actions/setup-r@v2
      with:
        Ncpus: 2
        use-public-rspm: true
    
    - name: Set R options    
      run: |
        echo "options(timeout = 600)" > $HOME/.Rprofile
        echo "options(BioC_mirror = 'https://packagemanager.rstudio.com/bioconductor')" >> $HOME/.Rprofile
    
    - name: Install pack
      run: install.packages('pak', dependencies = TRUE)
      shell: Rscript {0}
      
    - name: Install MASS
      run: pak::pkg_install("MASS")
      shell: Rscript {0}
      
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 1
        extra-packages: |
          MASS
          nnet
