on: 
  workflow_dispatch:
  push:

name: Installing MASS

jobs:
  install-mass:
    runs-on: ubuntu-20.04
    steps:  
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with: 
        extra-packages: MASS

    