on: 
  workflow_dispatch:
  push:

name: Installing MASS

jobs:
  install-mass:
    runs-on: ubuntu-20.04
    steps:  
    - uses: r-lib/actions/setup-r@v2
    
    - name: Install pack
      run: install.packages('pak')
      shell: Rscript {0}
      
    - name: Install MASS
      run: pak::pkg_install("MASS")
      shell: Rscript {0}